### ISSUE TITLE
Lighting Issues

### ISSUE THREAD

**Issue by myx0mat0sis** [leenlab2/reminiscence#188]
**Describe the bug**
Strange lighting shifts/movements happen when walking around the environment.

**To Reproduce**
1. Launch game
2. Walk and look around
3. See error

**Expected behavior**
Lighting corresponds regularly and with known sources.

**Screenshots**

https://github.com/leenlab2/reminiscence/assets/158416692/0e1a0ee7-6668-4c52-b0e6-1bde57ee55e2

https://github.com/leenlab2/reminiscence/assets/158416692/b285abb1-6ecb-45ee-94e9-3f0f22ae82f4

https://github.com/leenlab2/reminiscence/assets/158416692/d70dce41-92d4-4bef-86ce-22aaeb4d66bc

**Desktop (please complete the following information):**
 - OS: Windows
 - Version:10

**Additional context**
Unknown if 3rd lighting bug seen only happens after putting in the 2nd tape or was just not noticed prior.

**Comment by leenlab2** [comment]
After testing in unity, the issue seems to be from the point light above the stool:
![Image](https://github.com/leenlab2/reminiscence/assets/74102544/30fbc5c1-7e56-47f7-9a53-4df129335b72)

We should either remove that point light (it seems there is one already attached to the tape object) or hide it once the room lights turn on
